### ISSUE TITLE
Build Fails with fatal error: 'bits/libc-header-start.h' file not found During secp256k1-sys Compilation

### ISSUE THREAD

**Issue by gladguy** [Arch-Network/public-issues#3]
## Subject
Build Fails with fatal error: 'bits/libc-header-start.h' file not found During secp256k1-sys Compilation

### Description
I am encountering a build failure while attempting to start a demo application using the Arch CLI for the Arch Network. The build fails with a fatal error related to missing headers when compiling the secp256k1-sys dependency. The specific error message indicates that the file bits/libc-header-start.h cannot be found.

### Steps to reproduce

1. Set up the environment using Arch CLI.
2. Run the following command to start the demo application:
 `bash`
 `arch-cli demo start`
5. Observe the build process output.
The demo application should build and start successfully.

* Tell us how to reproduce this issue 
 `arch-cli demo start`

* Which commands triggered the issue, if any
`arch-cli demo start`

### Logs
fatal error: 'bits/libc-header-start.h' file not found
   26 | #include <bits/libc-header-start.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
This error occurs multiple times for the secp256k1-sys dependency.

**Environment Details:**

OS: [Ubuntu 22.04 LTS]
Rust Version: rustc 1.82.0 (f6e511eec 2024-10-15)
Cargo Version: cargo 1.82.0 (8f40fc59f 2024-08-21)
Arch CLI Version: arch-cli 0.1.4
Solana SDK Version: solana-cli 2.0.17 (src:7104d713; feat:607245837, client:Agave)

[Arch-error.log](https://github.com/user-attachments/files/17875249/Arch-error.log)

**Comment by hoffmabc** [comment]
Solana 2.x cli is not compatible unfortunately

**Comment by roethke** [comment]
Looks like downgrading to v1.18.x resolves this.
