### ISSUE TITLE
local validator not generating testnet addresses when connected to testnet rpc

### ISSUE THREAD

**Issue by Calgooon** [Arch-Network/public-issues#5]
### Description

After running the arch-cli init command, and changing the config file 'testnet' section to connect to a testnet rpc...
I am unable to deploy a smart contract because it is generating 'signet' addresses

### Environment

* rustc version (rustc 1.82.0)
* arch-cli version (arch-cli 0.1.4)
* OS and CPU architecture (MacOS Apple CPU)

### Steps to reproduce

* initialize arch-cli <br />
* Change config to connect to testnet <br />
* deploy contract against tesnet network

### Expected behaviour

Successful contract deploy

### Actual behaviour

Error that address is not for connected Bitcoin network

### Logs

johncalhoun@Johns-Mac-mini arch-cli % arch-cli deploy --network "testnet" --rpc-url http://localhost:9002
Welcome to the Arch Network CLI
Loading config for network: testnet
  → Loading configuration from /Users/johncalhoun/Library/Application Support/arch-cli/config.toml
  ✓ Loaded network-specific configuration for testnet
testnet
Deploying your Arch Network app...
Available folders to deploy:
  1. demo
  2. smart-contract
Enter the number of the folder you want to deploy (or 'q' to quit): 2
Deploying from folder: "/Users/johncalhoun/dev/arch/programs/projects/smart-contract"
  ℹ Building program...
  ℹ Cargo.toml found at: /Users/johncalhoun/dev/arch/programs/projects/smart-contract/app/program/Cargo.toml
  ℹ Current working directory: /Users/johncalhoun/dev/arch/programs/projects/smart-contract/app/program
  ✓ Program built successfully
Select a key to use as the program key: first-try
  ℹ Program ID: 4e9445dfaa21a1f86ba5b5b02c4e040bbae27ccdb248210d3ce74a10956b30f8
Wallet RPC URI: bitcoin-node.test.aws.archnetwork.xyz:49332/wallet/testwallet
Client connected: 000000000006bb3bbc094370946724e7be10bc4c4a33bbee133966a5fdb86924
  ✓ Wallet 'testwallet' is already loaded.
Network: testnet
Account Address: bcrt1pjxajqyrrc2y3mfgu3a4gkmlap72w5zmcscnavwm77njxv0zv0tlq30dtwc
Error: Account address does not match the configured Bitcoin network

**Comment by hoffmabc** [comment]
what does the testnet section of your /Users/johncalhoun/Library/Application Support/arch-cli/config.toml file have? What bitcoin network is your validator running on 9002 connected to?

**Comment by Calgooon** [comment]
The is what the testnet section looks like:
[networks.testnet]
  type =  "testnet"
  bitcoin_rpc_endpoint =  "bitcoin-node.test.aws.archnetwork.xyz"
  bitcoin_rpc_port =  "49332"
  bitcoin_rpc_user =  "bitcoin"
  bitcoin_rpc_password =  "uU1taFBTUvae96UCtA8YxAepYTFszYvYVSXK8xgzBs0"
  bitcoin_rpc_wallet =  "testwallet" 
  leader_rpc_endpoint =  "http://localhost:9002"

The validator running on 9002 was started with this command:

`arch-cli validator start --network "testnet"`

Shouldn't that start the validator on testnet or is there more to configure?

**Comment by Calgooon** [comment]
Was able to resolve myself by adding the --rpc-url flag to the deploy command and feeding it a client running testnet
